<?php
/**
 * Author: ' Silent
 * Time: 2017/9/22 10:05
 */

namespace Wx\Controller;


class PlatformSaleController extends BaseController
{
    public function _initialize()
    {
        // TODO: Change the autogenerated stub
    }

    /**
     * 首页
     */
    public function index()
    {
        $this->display();
    }
}