<?php
/**
 * Author: ' Silent
 * Time: 2017/11/13 16:45
 */

namespace Pc\Controller;

/**
 * 空调
 * Class ConditionerController
 * @package Pc\Controller
 */
class ConditionerController extends BaseController
{
    public $model = 'equipment';

    protected function _set_wheres(&$wheres)
    {
        $wheres = array('type' => 3);
    }

    public function index()
    {
        $this->assign('name','空调');
        $this->assign('equipment','空调');
        parent::index(); // TODO: Change the autogenerated stub
    }

    public function add()
    {
        $this->assign('type', 3);
        $this->assign('equipment', '空调');
        $this->display('edit');
    }
}