<?php
/**
 * Author: ' Silent
 * Time: 2017/11/13 17:28
 */

namespace Pc\Controller;


use Org\Net\Http;
use Pc\Model\HotelGetModel;
use Pc\Model\HotelModel;
use Pc\Model\HotelUserModel;
use Pc\Model\RoomTypeModel;
use Pc\Model\UserObjModel;
use Pc\Server\PageModel;

class HotelLoggedController extends BaseController
{
    public $model = 'hotel';
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 编辑和新增酒店
     */
    public function logged()
    {
        if (IS_AJAX || IS_POST) {
            $hotel = array();
            $hotel['name'] = I('post.name', '', 'trim');
            $hotel['ht_id'] = I('post.ht_id', 0, 'intval');
            $hotel['room_num'] = I('post.room_num', '', 'trim');
            $hotel['provice'] = I('post.provice', '', 'trim');
            $hotel['city'] = I('post.city', '', 'trim');
            $hotel['county'] = I('post.county', '', 'trim');
            $hotel['provice_id'] = I('post.provice_id', 0, 'intval');
            $hotel['city_id'] = I('post.city_id', 0, 'intval');
            $hotel['county_id'] = I('post.county_id', 0, 'intval');
            $hotel['area'] = I('post.area', '', 'trim');
            $hotel['tell'] = I('post.tell', '', 'trim');
            $hotel['img'] = I('post.img', '', 'trim');
            // 酒店缩略图地址(200*150)
            $hotel['thumb_img'] = I('post.thumb_img', '', 'trim');
            $hotel['shang_name'] = I('post.shangname', '', 'trim');
            $hotel['shang_tell'] = I('post.shang_tell', '', 'trim');
            $hotel['all_name'] = I('post.all_name', '', 'trim');
            $hotel['all_tell'] = I('post.all_tell', '', 'trim');
            $hotel['money_name'] = I('post.money_name', '', 'trim');
            $hotel['money_tell'] = I('post.money_tell', '', 'trim');
            $hotel['project_name'] = I('post.project_name', '', 'trim');
            $hotel['project_tell'] = I('post.project_tell', '', 'trim');
            $hotel['hotel_user_id'] = I('post.hotel_user_id', 0, 'intval');
            // 酒店客房类型
            $hotel['status'] = I('post.status');
            $id = I('post.id', 0, 'intval');
            $HotelGetId = I('post.HotelGetId', 0, 'intval');
            $hotel['data_room'] = I('post.dataroom');
            if ($hotel['img']) {
                // 转换字符串
                $hotel['img'] = implode(',', $hotel['img']);
            }
            if ($id) {
                // 编辑酒店
                $message = HotelModel::editHotel($id, $hotel, $HotelGetId);
            } else {
                // 新增酒店
                $message = HotelModel::addHotel($hotel);
            }
            $this->ajaxReturn($message);
        } else {
            $id = I('get.id', 0, 'intval');
            $HotelType = HotelModel::getHotelType();
            $HotelUser = HotelUserModel::getUserList();
            //房间类型房间数
            $RoomType = HotelModel::getList($id);
            $Hotel = HotelModel::findById($id);
            $HotelGteId = HotelGetModel::getId($Hotel['sale_id'], $id);
            $this->assign('id', $id);
            $this->assign('Hotel', $Hotel);
            $this->assign('HotelGetId', $HotelGteId);
            $this->assign('HotelUser', $HotelUser);
            $this->assign('RoomType', $RoomType);
            $this->assign('HotelType', $HotelType);
            $this->display();
        }
    }
}