<?php
/**
 * Author: ' Silent
 * Time: 2017/11/13 16:25
 */

namespace Pc\Controller;

/**
 * 保养类型
 * Class MaintenanceTypeController
 * @package Pc\Controller
 */
class MaintenanceTypeController extends BaseController
{
    public $model = 'equipment_oper';


    protected function _set_wheres(&$wheres)
    {
        $wheres = array('type' => array('eq', 1));
    }

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        $this->assign('name','保养');
        $this->assign('equipment', '保养');
        parent::index();
    }

    public function add()
    {
        $this->assign('type', 1);
        $this->assign('equipment', '保养');
        $this->display('edit');
    }
}