<?php
/**
 * Author: ' Silent
 * Time: 2017/9/20 9:50
 */

namespace Pc\Controller;

use Pc\Model\HotelModel;
use Pc\Model\RmainModel;

class MaintainController extends BaseController
{
    /**
     * 保养统计
     */
    public function _initialize()
    {
        // TODO: Change the autogenerated stub
    }

    /**
     * 首页加载
     */
    public function index()
    {
        // 准备所需要的数据
        $hotelData = HotelModel::getHotelName();
        $this->assign('hotel', $hotelData);
        $this->display();
    }

    /**
     * 保养统计图加载
     */
    public function maintainCount()
    {
        $this->display();
    }

    /**
     * 保养统计图筛选
     */
    public function lifterRepair()
    {
        $quyu = I('get.quyu', '', 'trim');
        $type = I('get.type');
        $htId = I('get.ht_id');
        $startTime = I('get.startTime');
        $endTime = I('get.endTime');
        $onedata = RmainModel::lifterMaintainMake($quyu, $type, $htId, $startTime ,$endTime);
        $this->assign('type', json_encode(i_array_column($onedata['list'], 'oper_name')));
        $this->assign('item', $onedata['item']);
        $twodata = RmainModel::lifterMainCountTrend($quyu, $type, $htId, $startTime ,$endTime);
        $this->assign('types', $twodata['month']);
        $this->assign('items', json_encode($twodata['list']));
        $this->display(T('RepairCount/maintainCounts'));
    }

    /**
     * 保养统计图加载
     */
    public function RepairCount()
    {
        $onedata = RmainModel::getMaintainMake();
        $this->assign('type', json_encode(i_array_column($onedata['list'], 'oper_name')));
        $this->assign('item', $onedata['item']);
        $twodata = RmainModel::getMainCountTrend();
        $this->assign('types', $twodata['month']);
        $this->assign('items', $twodata['list']);
        $this->display(T('RepairCount/maintainCount'));
    }

    /**
     * 根据酒店获取合同
     */
    public function getContaract()
    {
        $id = I('post.id', 0, 'intval');
        $type = I('post.type', 0, 'intval');
        $data = HotelModel::getHotelConID($id);
        $this->ajaxReturn($data);
    }

    /**
     * 获取数据
     */
    public function getRep()
    {
        $data = RmainModel::getMainCountTrend();
        $result['code'] = 0;
        $result['data'] = $data['list'];
        $this->ajaxReturn($result);
    }

}