<?php
/**
 * Author: ' Silent
 * Time: 2017/9/12 9:46
 */

namespace Pc\Controller;


use Pc\Model\HotelModel;
use Pc\Model\HotelUserModel;
use Pc\Model\UserObjModel;
use Pc\Server\PageModel;

class SalesClaimController extends BaseController
{
    private $user_id;
    private $listDataRows;

    /**
     * 平台销售人员经理认领列表
     */
    public function _initialize()
    {
        // TODO: Change the autogenerated stub
        $this->user_id = $this->identity()->getUserId();
        // 前台设置即可
        $this->listDataRows = 10;
    }

    /**
     * 获取用户登录对象
     */
    public function identity()
    {
        if (!$this->userObj) {
            $this->userObj = new UserObjModel();
        }
        return $this->userObj;
    }

    /**
     * 获取列表数据
     */
    public function listClaim()
    {
        $p = I('get.p', 1, 'intval');
        $countData = HotelModel::toDayCount();
        $count = HotelModel::listCount();
        $Page = new PageModel($count, $this->listDataRows);
        $data = HotelModel::listData($p, $Page->listRows);
        foreach ($data as $key => $val) {
            $data[$key]['hotel_status'] = HotelUserModel::checkUserStatus($this->user_id, $val['id']);
        }
        $this->assign('p', $p);
        $this->assign('page', $Page->show());
        $this->assign('count', $countData);
        $this->assign('data', $data);
        $this->display('index');
    }

    /**
     * 查看酒店详情
     */
    public function getListId()
    {
        $id = I('get.id', 0, 'intval');
        $p = I('get.p', 1, 'intval');
        $data = HotelModel::findById($id);
        // 检测酒店当前状态
        $status = HotelUserModel::checkUserStatus($this->user_id, $id);
        $this->assign('status', $status);
        $this->assign('id', $id);
        $this->assign('p', $p);
        $this->assign('data', $data);
        $this->display('seeHotel');
    }

}